apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nifi
  namespace: nifi
spec:
  serviceName: nifi-headless
  replicas: 1
  selector:
    matchLabels:
      app: nifi

  volumeClaimTemplates:
  - metadata:
      name: nifi-data
    spec:
      storageClassName: SC_NAME
      accessModes: ["ReadWriteMany"]
      resources:
        requests:
          storage: 5Gi

  template:
    metadata:
      labels:
        app: nifi
    spec:
      terminationGracePeriodSeconds: 120
      securityContext:
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch

      containers:
      - name: nifi
        image: 549103799643.dkr.ecr.us-west-1.amazonaws.com/nifi-1-26-0:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          name: http

        volumeMounts:
        - name: nifi-data
          mountPath: /opt/nifi/data

        startupProbe:
          tcpSocket:
            port: 8080
          periodSeconds: 15
          failureThreshold: 40
        readinessProbe:
          tcpSocket:
            port: 8080
          periodSeconds: 10
          failureThreshold: 12
